name: yxy
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2
  - pytorch
  - numba/label/dev
  - conda-forge
  - conda-forge/label/gcc7
  - conda-forge/label/broken
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - soumith
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - defaults
dependencies:
  - cudatoolkit=10.2
  - pytorch=1.9.0
  - torchvision
  - pydicom
  - tensorboard=1.15.0
  - tqdm
  - pandas
  - opencv
  - matplotlib
  - transformers=4.8.2
  - torchtext=0.10.1
  - libgcc-ng=9.3.0
  - __glibc=2.17
  - _openmp_mutex=4.5
  - llvm-openmp=9.0.1
  - openmp=11.1.0
  - tokenizers=0.10.1
  - pypy3.6=7.3.3
  


